### ISSUE TITLE
Two return statements in `view` sub-procedure

### ISSUE THREAD

**Issue by elehmer** [cal-adapt/climakitae#107]
The `threshold_panel.py` has a sub-procedure `view` that has 2 return statements. I don't think you can have 2...

https://github.com/cal-adapt/climakitae/blob/984d67e7950f333fc019b7b1c523fbe931b7b641/climakitae/threshold_panel.py#L163

**Comment by vicford** [comment]
I believe we should be keeping the first return statement because each subsequent call of view is in relation to a panel display. @ckingdon95 can you confirm before we revise this?

**Comment by nicolejkeeney** [comment]
See PR https://github.com/cal-adapt/climakitae/pull/122
