### ISSUE TITLE
Test for xarray DataArray a different way and rework asserts into if...raise statements in `timeseriestools.py`

### ISSUE THREAD

**Issue by elehmer** [cal-adapt/climakitae#108]
The line below can be rewritten better using `type(data) == xr.core.dataarray.DataArray` 

https://github.com/cal-adapt/climakitae/blob/984d67e7950f333fc019b7b1c523fbe931b7b641/climakitae/timeseriestools.py#L254

Also this whole section should be rewritten to use `if...raise` instead of the debugging `assert` statements...

**Comment by nicolejkeeney** [comment]
See PR https://github.com/cal-adapt/climakitae/pull/123
