### ISSUE TITLE
ck.view fails when using cmap parameter and station data

### ISSUE THREAD

**Issue by elehmer** [cal-adapt/climakitae#294]
I just noticed that `ck.view(data_to_use, lat_lon = False, cmap = "viridis")` fails for station data:

ValueError: failed to validate Line(id='2062', ...).line_color: expected either None or a value of type Color, got 'viridis'

**Comment by vicford** [comment]
This is a notebook guidance issue not climakitae code issue. Station data doesn't have xy coordinates so passing a variable cmap to it breaks this. Will modify the notebook slightly.
