### ISSUE TITLE
selections.show() produces long error when no downscaling method is selected

### ISSUE THREAD

**Issue by vicford** [cal-adapt/climakitae#295]
A really long param warning is produced above the selections panel if a user has not selected either `dynamical` or `statistical`. 

Use case:
- The selections.show() panel starts with `dynamical` default selected, but the user wants to retrieve `statistical` data instead
- User de-selects `dynamical` **first** and then selects `statistical`
    -  Issue does not occur if user selects `statistical` **first** and then de-selects `dynamical`

Desired behavior: Have some red text next to the dynamical and statistical checkboxes pop up stating that a downscaling option must be selected to proceed

**Comment by mdkoenig** [comment]
"Beefy" - Calvin, Eric, or the like

**Comment by elehmer** [comment]
https://github.com/cal-adapt/climakitae/pull/305
