### ISSUE TITLE
Progress bar breaks dask gateway cluster creation

### ISSUE THREAD

**Issue by bkg** [cal-adapt/climakitae#35]
It looks like the introduction of the `@progressbar` decorator from eff5d2b causes the "Can't pickle local object 'Param.widget.<locals>.link'" serialization error when attempting to use a dask cluster. By removing that decorator along with `@dask.delayed` from `_read_from_catalog()`, the dask cluster is working again.

**Comment by thenaomig** [comment]
Thanks for tracking that down. This was resolved by https://github.com/cal-adapt/climakitae/pull/36
