### ISSUE TITLE
Pip install on Ubuntu 20.04 broken

### ISSUE THREAD

**Issue by elehmer** [cal-adapt/climakitae#37]
I just tried to pip install climakitae on Ubuntu 20.04 in a new python virtualenv. Are there further system dependencies that I'm not aware of?

`pip install https://github.com/cal-adapt/climakitae/archive/main.zip`

```
Collecting https://github.com/cal-adapt/climakitae/archive/main.zip
  Downloading https://github.com/cal-adapt/climakitae/archive/main.zip
     | 27 kB 875 kB/s
Collecting cartopy
  Downloading Cartopy-0.20.2.tar.gz (10.8 MB)
     |████████████████████████████████| 10.8 MB 25.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/elehmer/.virtualenvs/clima/bin/python /tmp/tmpqcar8z8d get_requires_for_build_wheel /tmp/tmpnci4j6vw
       cwd: /tmp/pip-install-spdqzx3r/cartopy
  Complete output (1 lines):
  Proj version 6.3.1 is installed, but cartopy requires at least version 8.0.0.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/elehmer/.virtualenvs/clima/bin/python /tmp/tmpqcar8z8d get_requires_for_build_wheel /tmp/tmpnci4j6vw Check the logs for full command output.

```

**Comment by elehmer** [comment]
The strange thing is `cartopy 0.20.2` claims the requirement is `pyproj>=3.0.0`

**Comment by thenaomig** [comment]
We only ever use it inside a docker container, so we haven't had those
issues.

**Comment by bkg** [comment]
@elehmer that error refers to the Proj lib version, not pyproj, being incompatible with Cartopy 0.20. Try installing Cartopy 0.19 and then update climakitae:

    pip install cartopy==0.19.post1
    pip install --upgrade git+https://github.com/cal-adapt/climakitae.git

**Comment by elehmer** [comment]
I successfully installed using:

``pip install cartopy==0.19.post1
pip install --upgrade git+https://github.com/cal-adapt/climakitae.git``

On my Ubuntu 20.04 LTS machine at work in a clean python virtualenv.

In order to install cartopy on my Ubuntu 20.04 LTS virtual machine at home I had to first install:

``sudo apt install libgeos-dev
sudo apt install libproj-dev``

There are probably a few other Ubuntu system dependencies that I didn't trip over as well.
