### ISSUE TITLE
get_closest_gridcell logic needs to handle lat-lon inputs outside of spatial domain 

### ISSUE THREAD

**Issue by vicford** [cal-adapt/climakitae#388]
Context: SCE asked if whether using get_closest_gridcell returns a point in CA (or NV) if the lat lon passed is well outside the range

Example: Pass coordinates for SLC Utah with manual selections (not possible with GUI), and specifically have spatial res set to 3 km, and use get_closest_gridcell.

What actually happens is that the function works as intended and returns a gridcell in Nevada at the very edge of the 3km boundary. What we need to happen is that if the lat lon passed is well outside the range of the domain, get_closest_gridcell needs to return an error

**Comment by elehmer** [comment]
I will take a look at this tomorrow. Thx

**Comment by elehmer** [comment]
Fixed in #392
