### ISSUE TITLE
Grid mapping missing for hourly RH

### ISSUE THREAD

**Issue by bkg** [cal-adapt/climakitae#95]
The grid mapping attr is missing from the derived hourly RH. It's re-assigned after being dropped for the other vars, so RH needs to be included there as well. This came up during review of #94 where it needs to be worked around.
https://github.com/cal-adapt/climakitae/blob/392c870fba87fb8243d541a0efe0481a8f09326c/climakitae/derive_variables.py#L46-L50

**Comment by elehmer** [comment]
Can we switch to using wrf-python to calculate RH? It returns an `xarray.DataArray` and you can preserve the metadata with an option:

https://wrf-python.readthedocs.io/en/latest/user_api/generated/wrf.rh.html

**Comment by bkg** [comment]
It looks like all that's needed here is to add that var to the list which seems more straightforward than swapping dependencies. I believe wrf-python was used prior to switching to metpy which also has the benefit of already being included on the image, wrf-python is not.

**Comment by elehmer** [comment]
> It looks like all that's needed here is to add rh to the list of vars which seems more straightforward than swapping dependencies. I believe wrf-python was used prior to switching to metpy which also has the benefit of already being included on the image, wrf-python is not.

Ahh, ok that makes perfect sense. Thanks for the history. Yeah, let's go with the easy fix. I looked at the MetPy github and went over the changes from 1.1.0 to 1.3.0 and I don't see anything touching this issue so I don't think upgrading MetPy will help.
